// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
/// 3D vector, right-handed Y-up (Bevy convention).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Vec3 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}
impl ::core::fmt::Debug for Vec3 {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Vec3")
            .field("x", &self.x)
            .field("y", &self.y)
            .field("z", &self.z)
            .finish()
    }
}
/// Linear sRGB color, each channel in 0.0..=1.0.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Rgba {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}
impl ::core::fmt::Debug for Rgba {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Rgba")
            .field("r", &self.r)
            .field("g", &self.g)
            .field("b", &self.b)
            .field("a", &self.a)
            .finish()
    }
}
/// Closed mesh vocabulary: every backend handles every variant exhaustively.
#[repr(u8)]
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub enum MeshKind {
    Sphere,
    Cube,
    Plane,
    Cylinder,
}
impl ::core::fmt::Debug for MeshKind {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            MeshKind::Sphere => f.debug_tuple("MeshKind::Sphere").finish(),
            MeshKind::Cube => f.debug_tuple("MeshKind::Cube").finish(),
            MeshKind::Plane => f.debug_tuple("MeshKind::Plane").finish(),
            MeshKind::Cylinder => f.debug_tuple("MeshKind::Cylinder").finish(),
        }
    }
}
impl MeshKind {
    #[doc(hidden)]
    pub unsafe fn _lift(val: u8) -> MeshKind {
        if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
        }
        match val {
            0 => MeshKind::Sphere,
            1 => MeshKind::Cube,
            2 => MeshKind::Plane,
            3 => MeshKind::Cylinder,
            _ => panic!("invalid enum discriminant"),
        }
    }
}
/// One renderable thing: positioned, scaled, colored primitive with an
/// optional label and a provenance `source` string.
#[derive(Clone)]
pub struct SceneNode {
    pub pos: Vec3,
    pub scale: f32,
    pub mesh: MeshKind,
    pub color: Rgba,
    pub label: Option<_rt::String>,
    pub source: _rt::String,
}
impl ::core::fmt::Debug for SceneNode {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SceneNode")
            .field("pos", &self.pos)
            .field("scale", &self.scale)
            .field("mesh", &self.mesh)
            .field("color", &self.color)
            .field("label", &self.label)
            .field("source", &self.source)
            .finish()
    }
}
/// Renderer-neutral camera; up is +Y.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Camera {
    pub eye: Vec3,
    pub look_at: Vec3,
}
impl ::core::fmt::Debug for Camera {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Camera")
            .field("eye", &self.eye)
            .field("look-at", &self.look_at)
            .finish()
    }
}
/// The whole scene: the entire renderer contract.
#[derive(Clone)]
pub struct Scene {
    pub nodes: _rt::Vec<SceneNode>,
    pub camera: Camera,
    pub background: Rgba,
}
impl ::core::fmt::Debug for Scene {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Scene")
            .field("nodes", &self.nodes)
            .field("camera", &self.camera)
            .field("background", &self.background)
            .finish()
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_hello_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::hello(_rt::string_lift(bytes0));
    let ptr2 = _RET_AREA.0.as_mut_ptr().cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(4).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_hello<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(4).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_render_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::render(_rt::string_lift(bytes0));
    let ptr2 = _RET_AREA.0.as_mut_ptr().cast::<u8>();
    let Scene { nodes: nodes3, camera: camera3, background: background3 } = result1;
    let vec9 = nodes3;
    let len9 = vec9.len();
    let layout9 = _rt::alloc::Layout::from_size_align_unchecked(vec9.len() * 56, 4);
    let result9 = if layout9.size() != 0 {
        let ptr = _rt::alloc::alloc(layout9).cast::<u8>();
        if ptr.is_null() {
            _rt::alloc::handle_alloc_error(layout9);
        }
        ptr
    } else {
        ::core::ptr::null_mut()
    };
    for (i, e) in vec9.into_iter().enumerate() {
        let base = result9.add(i * 56);
        {
            let SceneNode {
                pos: pos4,
                scale: scale4,
                mesh: mesh4,
                color: color4,
                label: label4,
                source: source4,
            } = e;
            let Vec3 { x: x5, y: y5, z: z5 } = pos4;
            *base.add(0).cast::<f32>() = _rt::as_f32(x5);
            *base.add(4).cast::<f32>() = _rt::as_f32(y5);
            *base.add(8).cast::<f32>() = _rt::as_f32(z5);
            *base.add(12).cast::<f32>() = _rt::as_f32(scale4);
            *base.add(16).cast::<u8>() = (mesh4.clone() as i32) as u8;
            let Rgba { r: r6, g: g6, b: b6, a: a6 } = color4;
            *base.add(20).cast::<f32>() = _rt::as_f32(r6);
            *base.add(24).cast::<f32>() = _rt::as_f32(g6);
            *base.add(28).cast::<f32>() = _rt::as_f32(b6);
            *base.add(32).cast::<f32>() = _rt::as_f32(a6);
            match label4 {
                Some(e) => {
                    *base.add(36).cast::<u8>() = (1i32) as u8;
                    let vec7 = (e.into_bytes()).into_boxed_slice();
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    ::core::mem::forget(vec7);
                    *base.add(44).cast::<usize>() = len7;
                    *base.add(40).cast::<*mut u8>() = ptr7.cast_mut();
                }
                None => {
                    *base.add(36).cast::<u8>() = (0i32) as u8;
                }
            };
            let vec8 = (source4.into_bytes()).into_boxed_slice();
            let ptr8 = vec8.as_ptr().cast::<u8>();
            let len8 = vec8.len();
            ::core::mem::forget(vec8);
            *base.add(52).cast::<usize>() = len8;
            *base.add(48).cast::<*mut u8>() = ptr8.cast_mut();
        }
    }
    *ptr2.add(4).cast::<usize>() = len9;
    *ptr2.add(0).cast::<*mut u8>() = result9;
    let Camera { eye: eye10, look_at: look_at10 } = camera3;
    let Vec3 { x: x11, y: y11, z: z11 } = eye10;
    *ptr2.add(8).cast::<f32>() = _rt::as_f32(x11);
    *ptr2.add(12).cast::<f32>() = _rt::as_f32(y11);
    *ptr2.add(16).cast::<f32>() = _rt::as_f32(z11);
    let Vec3 { x: x12, y: y12, z: z12 } = look_at10;
    *ptr2.add(20).cast::<f32>() = _rt::as_f32(x12);
    *ptr2.add(24).cast::<f32>() = _rt::as_f32(y12);
    *ptr2.add(28).cast::<f32>() = _rt::as_f32(z12);
    let Rgba { r: r13, g: g13, b: b13, a: a13 } = background3;
    *ptr2.add(32).cast::<f32>() = _rt::as_f32(r13);
    *ptr2.add(36).cast::<f32>() = _rt::as_f32(g13);
    *ptr2.add(40).cast::<f32>() = _rt::as_f32(b13);
    *ptr2.add(44).cast::<f32>() = _rt::as_f32(a13);
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_render<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(4).cast::<usize>();
    let base7 = l0;
    let len7 = l1;
    for i in 0..len7 {
        let base = base7.add(i * 56);
        {
            let l2 = i32::from(*base.add(36).cast::<u8>());
            match l2 {
                0 => {}
                _ => {
                    let l3 = *base.add(40).cast::<*mut u8>();
                    let l4 = *base.add(44).cast::<usize>();
                    _rt::cabi_dealloc(l3, l4, 1);
                }
            }
            let l5 = *base.add(48).cast::<*mut u8>();
            let l6 = *base.add(52).cast::<usize>();
            _rt::cabi_dealloc(l5, l6, 1);
        }
    }
    _rt::cabi_dealloc(base7, len7 * 56, 4);
}
pub trait Guest {
    /// Trivial smoke-test export to de-risk the round-trip.
    fn hello(name: _rt::String) -> _rt::String;
    /// The real export: parse a CEG `scores` envelope (JSON) and return a typed
    /// Scene. Pure, total, deterministic; cannot perform IO because the world
    /// grants no imports.
    fn render(attestation_json: _rt::String) -> Scene;
}
#[doc(hidden)]
macro_rules! __export_world_view_form_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[export_name = "hello"] unsafe extern "C" fn export_hello(arg0
        : * mut u8, arg1 : usize,) -> * mut u8 { $($path_to_types)*::
        _export_hello_cabi::<$ty > (arg0, arg1) } #[export_name = "cabi_post_hello"]
        unsafe extern "C" fn _post_return_hello(arg0 : * mut u8,) { $($path_to_types)*::
        __post_return_hello::<$ty > (arg0) } #[export_name = "render"] unsafe extern "C"
        fn export_render(arg0 : * mut u8, arg1 : usize,) -> * mut u8 {
        $($path_to_types)*:: _export_render_cabi::<$ty > (arg0, arg1) } #[export_name =
        "cabi_post_render"] unsafe extern "C" fn _post_return_render(arg0 : * mut u8,) {
        $($path_to_types)*:: __post_return_render::<$ty > (arg0) } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_view_form_cabi;
#[repr(align(4))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 48]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 48]);
#[rustfmt::skip]
mod _rt {
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_f32<T: AsF32>(t: T) -> f32 {
        t.as_f32()
    }
    pub trait AsF32 {
        fn as_f32(self) -> f32;
    }
    impl<'a, T: Copy + AsF32> AsF32 for &'a T {
        fn as_f32(self) -> f32 {
            (*self).as_f32()
        }
    }
    impl AsF32 for f32 {
        #[inline]
        fn as_f32(self) -> f32 {
            self as f32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_view_form_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_view_form_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_view_form_impl as export;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:demo:view-form@0.1.0:view-form:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 451] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc3\x02\x01A\x02\x01\
A\x12\x01r\x03\x01xv\x01yv\x01zv\x03\0\x04vec3\x03\0\0\x01r\x04\x01rv\x01gv\x01b\
v\x01av\x03\0\x04rgba\x03\0\x02\x01m\x04\x06sphere\x04cube\x05plane\x08cylinder\x03\
\0\x09mesh-kind\x03\0\x04\x01ks\x01r\x06\x03pos\x01\x05scalev\x04mesh\x05\x05col\
or\x03\x05label\x06\x06sources\x03\0\x0ascene-node\x03\0\x07\x01r\x02\x03eye\x01\
\x07look-at\x01\x03\0\x06camera\x03\0\x09\x01p\x08\x01r\x03\x05nodes\x0b\x06came\
ra\x0a\x0abackground\x03\x03\0\x05scene\x03\0\x0c\x01@\x01\x04names\0s\x04\0\x05\
hello\x01\x0e\x01@\x01\x10attestation-jsons\0\x0d\x04\0\x06render\x01\x0f\x04\0\x1e\
demo:view-form/view-form@0.1.0\x04\0\x0b\x0f\x01\0\x09view-form\x03\0\0\0G\x09pr\
oducers\x01\x0cprocessed-by\x02\x0dwit-component\x070.220.0\x10wit-bindgen-rust\x06\
0.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
